translator = {
    "ExpenseRecord": "Registro de Despesa",
    "CategoryEnum": "Categoria",
    "description": "Descrição",
    "category": "Categoria",
    "amount": "Valor",
    "payment_method": "Método de pagamento",
    "vendor": "Fornecedor",
    "notes": "Notas",
    "food": "Alimentação",
    "transport": "Transporte",
    "health": "Saúde",
    "education": "Educação",
    "housing": "Moradia",
    "entertainment": "Entretenimento",
    "shopping": "Compras",
    "services": "Serviços",
    "travel": "Viagem",
    "taxes": "Impostos",
    "other": "Outro",
}