translator = {
    "ExpenseRecord": "Registro de Despesa",
    "CategoryEnum": "Categoria",
    "description": "descrição",
    "category": "categoria",
    "amount": "valor",
    "payment_method": "método de pagamento",
    "vendor": "fornecedor",
    "notes": "notas",
    "food": "alimentação",
    "transport": "transporte",
    "health": "saúde",
    "education": "educação",
    "housing": "moradia",
    "entertainment": "entretenimento",
    "shopping": "compras",
    "services": "serviços",
    "travel": "viagem",
    "taxes": "impostos",
    "other": "outro",
}